networks:
  default:
    driver: bride 
    name: roboshop
    external: true  # I created a network already using docker network create roboshop

services:
  mongodb:
    image: pardhupersonal72/mongodb:v1
    conatiner_name: mongodb
  catalogue:
    image: pardhupersonal72/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb

  redis:
    image: redis:7.0
    container_name: redis
  
  user:
    image: pardhupersonal/cart:v1
    container_name: cart
    depends_on: 
    - catalogue
    - redis

  mysql:
    image: pardhuperonal72/mysql:v1
    conatiner_name: mysql
  shipping:
    image: pardhupersonal72/shipping:v1
    container_name: shipping
    depends_on: 
    - mysql
    - cart

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEAFULT_PASS: roboshop123

  payment:
    image: pardhupersonal72/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT1: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AQMP_USER: roboshop
      AMQP_PASS: roboshop123S
    depends_on: 
    - rabbitmq
    - cart
    - user
  frontend:
    image: pardhupersonal72S/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment